---
layout: cv
title: Spencer Payne's CV
---
# Spencer Payne


<div id="webaddress">
<a href="spayne22802@gmail.com">spayne22802@gmail.com</a>
| <a href="https://www.linkedin.com/in/spencer-payne-95090428b">My LinkedIn page</a>
</div>


## Currently

Studying Data Science at BYU-Idaho

### Specializing in

Business Analytics


## Education

`2016-2020`

__Royal High School.__





## Awards


-Eagle Scout Individual Project Lead, Boy Scouts of America

-Water Polo Team Captain, Royal High School






## Occupation

Family Psychological Services @ Agoura Hills, California  <br>
__Testing Center Supervisor__  <br>
'Mar. 2023 – Present'  <br>

•	Provided patients with psychological testing from initial intake appointment until results interview with a licensed clinician.<br>

•	Increase the ease that patients finished with psychological testing by creating excel sheets that mimicked several tests given to patients which could be filled out virtually.<br>

•	Created analytics documents to help clinicians know their patient counts within a day/month/year which helped clinicians make informed decisions.<br>


The Church of Jesus Christ of Latter-day Saints	@ Mexico City, Mexico  <br>
__Missionary/IT Lead__  <br>
'May. 2021 – Mar. 2023'  <br>

•	Talked to people every day for two years about the message of The Church of Jesus Christ of Latter-Day Saints, meeting with people in public and in their homes.<br>

•	Collected data from missionaries about phone usages and digital success with Facebook to allow leadership to make changes on how efficiently missionaries used time, resources and how to communicate our message more clearly.<br>

•	Led a team of 4 missionaries that oversaw digital content production on a Facebook page that geographically covered the southern half of Mexico City.<br>

Sub Zero Ice Cream @ Simi Valley, CA  <br>
__Store Associate__  <br>
'June. 2021 – Sept. 2021'  <br>

•	Served customers custom ice cream frozen with liquid nitrogen, using nitrogen as entertainment for store goers entering the establishment.<br>

Rancho Simi Community Pool @ Simi Valley, CA <br> 
__Swim Instructor/Lifeguard__  <br>
'May. 2019 – Sept. 2021'  <br>


•	Taught swimming classes alone and with a co-teacher for children who’s ages ranged from 3 – 12-years-old.<br>

•	Monitored patrons within the facility to insure safety and responded to emergencies quickly to keep issues at a minimum.<br>



<!-- ### Footer

Last updated: May 2013 -->